const DELETED = 'DELETED';
const REMOVED = 'REMOVED';
const ADDED = 'ADDED';
const NEW_NOTIFICATION = 'NEW_NOTIFICATION';

exports.DELETED = DELETED;
exports.REMOVED = REMOVED;
exports.ADDED = ADDED;
exports.NEW_NOTIFICATION = NEW_NOTIFICATION;
